# -*- coding: utf-8 -*-
"""ExoplanetAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gsl2wBPPcNdYyfEG8Jp3zIcU4q2-j3WN

# Exoplanet Analysis

Goal:
Analyze confirmed exoplanets to understand size, stellar energy, and detection confidence.

Steps:
- Filter confirmed planets
- Clean relevant features
- Create size categories
- Analyze distributions
- Export for Tableau

Import block
"""

import pandas as pd
import numpy as np
from google.colab import files

"""Collab Block"""

from google.colab import drive
path = '/content/drive/MyDrive/exoplanets.csv'

df = pd.read_csv(path)

"""Column Exploration"""

df.columns.tolist()

"""# filter confirmed discoveries only and keep columns relevant to question

"""

df_raw = df.copy()

df_confirmed = df_raw[df_raw['koi_disposition'] == 'CONFIRMED']

df_confirmed = df_confirmed[['kepoi_name','koi_prad','koi_insol','koi_score']].dropna()

df_confirmed = df_confirmed.sort_values(by='koi_score', ascending=False)
df_confirmed.head()

"""Size Categories"""

df_confirmed['size_category'] = pd.cut(
    df_confirmed['koi_prad'],
    bins=[0,1.5,3,6,20]
    ,labels=['earth-like','super-earth-like','neptune-like','Gas-Giant']

)
df_confirmed.head()

"""Distributions"""

size_dist = df_confirmed['size_category'].value_counts().reset_index()
size_dist.columns = ['size_category','count']
size_dist

"""Stellar Energy"""

energy_bins = pd.cut(
    df_confirmed['koi_insol'],
    bins=[0,10,100,500,2000],
    labels=['Low','Moderate','High','Extreme']
)
energy_dist = energy_bins.value_counts().reset_index()
energy_dist.columns = ['energy_level', 'count']
energy_dist

"""Confidence by size"""

confidence_by_size = df_confirmed.groupby('size_category')['koi_score'].mean().reset_index()
confidence_by_size

"""Export and download clean csv"""

pd.DataFrame.to_csv(confidence_by_size, 'confidence_by_size.csv')
pd.DataFrame.to_csv(df_confirmed, 'confirmed_exoplanets.csv')
pd.DataFrame.to_csv(energy_dist, 'energy_dist.csv')
pd.DataFrame.to_csv(size_dist, 'size_dist.csv')

files.download("confirmed_exoplanets.csv")
files.download("size_dist.csv")
files.download("energy_dist.csv")
files.download("confidence_by_size.csv")